### ISSUE TITLE
Paxels / AOITs

### ISSUE THREAD

**Issue by Thiana** [SilentChaos512/SilentGems#138]
Could you please consider implementing paxels/aoits? Thank you.

**Comment by SilentChaos512** [comment]
I can't remember why I haven't already, probably some silly reason. I'll get on it as soon as possible.

**Comment by SilentChaos512** [comment]
Got most/all the code in place, just missing textures/models. One thing I'm on the fence about is whether or not they should be "super tools" (only super-tier is allowed, like katanas and scepters). That's how I currently have them set, although it would be easy to change. I just feel like having paxels right from the start might be too much. Let me know your thoughts.

**Comment by Thiana** [comment]
That was fast. Thanks :)

I can see three viable paths:

(1) Super tier only and the retain the  special abilities, so they would be late(r) game.

(2) Low tier only, which means the player has to choose specialized and powerful (fast/aoe/etc) or generic and just does the minimum for the job. I'd even apply a penalty of sorts by reducing speed/damage/durability by 20% or so versus a specialized tool. 

(3) Combine both paths. The super tier paxel can use the special abilities, but still has a penalty (10%) over the specialized tools.

I lean towards the second option since I see it as a generic tool rather than a more powerful specialized tool. This way of you're just around your base/building you're using a paxel but if you go mining/logging/hunting you use the specialized tools. If applying that sort of overall penalty isnt possible with your code, then I'd go with super tier only (P1).

**Comment by DennHenda** [comment]
While I enjoy the thought of having an all in one super tool, I agree that they should probably only be lower or normal tier with penalties. I think that I would never craft the pickaxe, axe or shovel again if I had the option of a super paxel.

It might take a lot away from your mod if no one bothers to craft anything​ from super tier except paxels.

**Comment by jazzyworld** [comment]
i dont feel an Aiot or Paxel would take away from the mod at all, you still need to craft the initial components in order to combine them. in fact, without an 'item repairer', the durability would go down faster on the single item, forcing  you to make each of the combined tools again and again, spending more of the hard earned gems every time. personally, i use a flint axe, hoe, shovel and just throw on emerald tips, increasing their durability and harvest speed. really the best combined tool that is needed is a melee/pickaxe combo, so when yer mining and a mob pops up, you dont have to worry about switching from pickaxe to sword or katana etc.
actually, the best thing i can think of in this situation would be a 'tool' all in one (shovel+hoe+axe), plus add a magic use to pickaxes, possibly something that also shoots behind you or in an expanding ring in all directions centered around you or maybe even homing fireballs that seek out the nearest hostile.

**Comment by DennHenda** [comment]
I mean without any sort of reduced speed or such, it might take away from other tools. Super tier paxels are great if properly balanced, I'd just like them not too overpowered as to overshadow the main tools.
Reading over Thiana's ideas again, I also like the third option of super tier having an ability, while still having a penalty. Similar to how Silent's Gems already handles tools. Adding a reduced speed and/or durability for them too.

Any way their implemented I won't complain, I love this mod. Just thought I'd offer some feedback as a player.

**Comment by SilentChaos512** [comment]
Thanks for all the feedback. I thought I mentioned this here, but seems it's only in the changelog: Paxels currently are super-tier only, have 25% more durability, 25% less harvest speed, and repairs are 30% less effective (it would take ~6 regular gems to fully repair a broken supercharged paxel). They also require 6 materials (gems, etc.) to craft.
One idea I had (although I don't really like it) is to add an item that requires one of each gem to craft into the recipe. Sounds like too big of a headache for normal play though.
