### ISSUE TITLE
Tool Ideas

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/SilentGems#143]
**Suggestions and feedback are always welcome!**

Dug up this "ancient" comment I had almost forgotten about from Oct 22, 2015, copied verbatim from CurseForge:

>...
-A "Battle-axe":a double axe blades, will do 4x the damage of all gem swords plus when right click will do a dash increasing the attack with strenght II and decrease the speed with slowness II. The craft it with three sticks on the middle and two gems on each side.
-A "Mace": a suqare tip like weapon, will slow te user but do almost the same damage as a battle-axe. The craft for this will be one stick on the middle and a 3x2 above it.
-A "Spear": a long weapon type, distance of 2 block attack and the damage equals a mace. This is crafted with two sticks on diagonal and a gem on the tip.
-A "Dagger": most close combat weapon, will do -1x the damage of a normal gem sword but the speed of attack is highter. The craft is simple: one stick on the middle and a gem above it.
-A "Katana": as a dagger is most close weapon, but the damage is the same as a normal gem sword but (at all >:]) the speed is like HUGEST compare as a dagger. This thing is crafted at this: one stick at diagonal plus two gems at the same direction ;).
-A "Rapier": this is simular as a sword but, will ignore armor defence. It's crafted the seme as a Katana but, the opposite direction.
-And at the final, "Long-Sword": identical as a spear but do the same gem  sword damage. This beast is crafted this way: one stick at the middle, three gems above it and at the middle (again :P) a gem.
...

Obviously just some ideas to consider. Some suggestions seem redundant (e.g. battleaxe/mace). And I honestly dislike slow weapons. Too difficult to work with in Minecraft. Katanas are already a thing and daggers are on the way. Not sure what else I'll add, but I wanted to record the comment here.

**Comment by yggdrasil75** [comment]
with the fuller implementation of chaos, it might be fun to have bardic instruments, ie: a spinel banjo could heal the player, and a pan flute make living creatures flee.
A trident would be nice, it could deal damage of a low value multiple time, this could be useful if  mod that allows changes to health is installed, as a player with max health may not have on as much armor compared to a player of very little health.
If a katar was in the mod then it could be hidden when first equipped, and not visible in the hand until it has been damaged.
a few different types of shields would be nice, for example, tower shield always protects or a shield that does not slow down the player but is broken much quicker. 
I do not know what the recipes would be for this, because I am currently making a modpack that implements thousands of recipes via minetweaker for every tool weapon and item to replace these with various other mods worktable alternatives. Hopefully armory mod will add support so I can use that.

**Comment by aziel13** [comment]
Weapon ideas:
A halberd: crafted like an ax but with an additional gem on the middle left and middle right. Would have reach like the spear but attacks in a chopping overhand motion. On charge attack should do more damage or knock-back.
Gem flail: a ball and chain flail. slow to use, has extra range, and Ignores or does partial damage to shield using opponents.

Non weapon ideas:
Gem Sheers: 2 gems crafted in the same manner as normal sheers. repairable with a mass sheer functionality that can sheer a 3x3x3 cube of leaves or sheep.
Gem Bucket: bucket that is made of gems. alternative ability would be able to fill containers in your inventory.
Gem Grafter(if forestry is enabled) 
Gem Bee Net(if forestry is enabled)
