### ISSUE TITLE
[1.11.2 - 2.3.13-181] - Creative Menu Crash

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [SilentChaos512/SilentGems#160]
Crash Happens when I click the weapons tab!

https://pastebin.com/kCHQZR97

Thanks SC! let me know if u  need anything else.

**Comment by EPIICTHUNDERCAT** [comment]
Second crash, this happen in the mods own tools and armor tab.

https://pastebin.com/m8jrn8bA

Seems similar or even the same but in 2 different tabs :)

**Comment by SilentChaos512** [comment]
That's a strange one. The crash reports show the mod trying to make swords/shields out of... air. And it's not happy about that. It's like something is messing up my tool part registry. But as far as I know, Extra Parts is the only other mod that registers tool parts. I don't crash with just those.

If you can figure out a specific mod that seems to cause this, let me know. Otherwise I'll give you a build that will log more information on the crash. But I won't be able to set that up until tomorrow.

**Comment by EPIICTHUNDERCAT** [comment]
Ill take that, sure. Ill let you know what happens. We do have Extra Parts in the pack though.

**Comment by SilentChaos512** [comment]
I'm adding the extra information in the next build. It will still crash, but it will tell us what tool part is broken/corrupted/whatever.

**Comment by EPIICTHUNDERCAT** [comment]
sounds perfect to me :) let me know when its ready

**Comment by SilentChaos512** [comment]
New build is up: https://minecraft.curseforge.com/projects/silents-gems/files/2432624

**Comment by SilentChaos512** [comment]
Possibly same issue as SilentChaos512/SGExtraParts#5. If it is, I've got it fixed.
