### ISSUE TITLE
[1.12]  cascading worldgen lag

### ISSUE THREAD

**Issue by Morpheus1101** [SilentChaos512/SilentGems#181]
Each time anyone on the sever goes to a new chunk this msg along with a few other mods saying the exact same thing spams the console.....

[04:46:11] [Server thread/WARN]  [FML]: Silent's Gems loaded a new chunk (-521, -5 Dimension: 6) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by SilentChaos512** [comment]
I just saw that myself. Not sure what's causing it. Seems rare enough that it doesn't cause any actual lag at least.

**Comment by TechnicianLP** [comment]
Cascading Worldgen is something that should not be ignored! 
It for one spams the console in newer versions, but the reason for it is much simpler: the tiny delays of generating new chunks (that would normally not be neccesary) can add up to minutes for generating the originally requested chunk (depending on rng as worldgen is random)(in some cases it can also lead to stackoverflow-exceptions due to the recursion that occurs when generating chunks while generating chunks ....) i may seem small - but it definitly can (and will cause) major problems
If you dont know whats causing it or how to fix it - ask in #minecraftforge on the esper irc-network
(most commonly this issue is caused by missing offsets)

**Comment by SilentChaos512** [comment]
I know, I plan to look into which worldgen feature is causing this when I get a chance. I've already seen how to fix it. There are features I'm not currently offsetting, but they generate only single blocks, so I'm not sure if that's the issue (worth a shot I guess). I think the issue is chaos ore, which spawns large veins by default. Even with the standard (8, 8) offset, I think it could still spill over.

**Comment by SilentChaos512** [comment]
Looks like single block features can load other chunks due to block updates. Well, guess that makes this an easier fix than I thought.
