### ISSUE TITLE
[1.10.2] Putting on armor makes my skin black.

### ISSUE THREAD

**Issue by senpaisayss** [SilentChaos512/SilentGems#184]
I can see the item when it's in my search bar, hot bar, in my hand. When I put the item on my player my skin turns black...anyway to fix this for a youtube smp?

**Comment by SilentChaos512** [comment]
I recall armor rendering being broken in some cases, which MC version are
you on? Do you have OptiFine installed?

**Comment by senpaisayss** [comment]
Version 1.10.2 & yes I have optifine installed :(

**Comment by SilentChaos512** [comment]
Removing OptiFine may fix the issue, not sure.  But I don't think armor
will even fully render in 1.10.2 right now. Will look into this more when I
get home.

**Comment by SilentChaos512** [comment]
I can't get the black textures in 1.10.2 with or without OptiFine, although I have seen that happen before. But the rendering is still broken and spits out a steady stream of errors in the console...

I think I'll just make a dedicated 1.10.2/1.11.2 build. 1.12 made some changes in rendering. Compatibility between all 3 versions should be possible, but I think I'm ready to give up on that. I'd rather give players of older versions a stable experience, rather than new features with lots of bugs.

**Comment by SilentChaos512** [comment]
Released a new version (marked 1.11.2, works on 1.10.2). Let me know if everything works OK.

**Comment by senpaisayss** [comment]
Nope when I put the armor on it's still rending just black :( dang would have been awesome for my smp too

**Comment by SilentChaos512** [comment]
I made a new build to better support 1.10.2 and 1.11.2, try that version
(think it's labeled 1.11.2-2.4.5). Pretty sure armor is rendering normally
in that build. The downside is 1.10/11 will be bugfix-only, but I think
it's for the best.

**Comment by senpaisayss** [comment]
Nope, I guess it's just not meant to be :(

**Comment by senpaisayss** [comment]
Weird it shows up on an armor stand but when the player is wearing it it's just all black
