### ISSUE TITLE
Server/Client crash seems to be related to chaos nodes

### ISSUE THREAD

**Issue by tfox83** [SilentChaos512/SilentGems#214]
Silent Gems 1.12-2.5.3-227
Silent Lib 1.12-2.2.9-89
SGExtraParts 1.12-1.4.0-30
Minecraft Version: 1.X12.2

Crash Report: https://pastebin.com/PVtR0byz

Happening to two different people in two different areas on the server.  Crashes client and server upon log in.

Thanks!

**Comment by SilentChaos512** [comment]
Try turning on the "Direct Transfer" option under the "chaos" category in the config. That tends to help with node-related crashes on servers.

This kind of issue is very hard to track down. I can't even tell if my entities are at fault because the error happens so deep into vanilla classes. It could be another mod adding entities in the wrong thread. Or it could be mine. I'll try tweaking a couple of things for the next build.

**Comment by tfox83** [comment]
Will give that a try, thanks for the fast response!

**Comment by tfox83** [comment]
Tried that config option with no luck.  Is it safe to disable the nodes for new worlds?  I have this in the new Horizons 3 FTB modpack that is still in beta testing.  If I can just leave them disabled without killing progression within the mod, Ill just do that for now for release of the pack.  Thanks again for your time.

**Comment by SilentChaos512** [comment]
Disabling nodes will be fine. They're convenient, but not essential. But I do recommend leaving direct transfer on, since pylons use the same entities that are causing the crash. I should probably ditch the whole entity-based transfer system. It's interesting, but causes too many issues.

**Comment by SilentChaos512** [comment]
Should be fixed as of version 2.5.6. I removed the entities that chaos nodes create and just transfer effects directly instead.
