### ISSUE TITLE
Decoration doesn't work [Horizons 3]

### ISSUE THREAD

**Issue by Fortanono** [SilentChaos512/SilentGems#220]
### Versions

Minecraft Version: 1.12.2 (Playing Horizons 3)
Silent's Gems Version: 2.5.6-232
Silent Lib Version: 2.2.10-91

### Expected behavior

- Decoration should affect the look of your tool

### Actual behaviour

- Decoration doesn't; textures will be the same, or, if you put on too much, missing.

### Steps to reproduce the problem

1. Grab a gem tool (I've only tried the pickaxes, regular and supercharged, might work for other tools)
2. Decorate it.
3. ...
4. Profit

**Comment by SilentChaos512** [comment]
Decorating was technically removed, although there is still some leftover pieces. I didn't know about the missing models issues, thanks for reporting that. I also assume I need to fix the in-game manual.

**Comment by Fortanono** [comment]
Aww. I really liked that feature. I assume it was too technically difficult to keep?

**Comment by SilentChaos512** [comment]
You could say the new gems in the End are the reason. I couldn't get colors I was happy with without creating entirely new textures. With the Nether gems I could cheat a bit and just darken the normal ones. So instead of doubling the already large number of textures, I thought it would be better to just have one texture per tool head. At least the dark gem tools look a lot better now, having their own textures. I think that's worth it.

**Comment by Fortanono** [comment]
Alright, maybe keep it as an Overworld-only thing? Please? It's your mod, but that was honestly the best feature.

**Comment by SilentChaos512** [comment]
No, it would be too difficult to restrict it to certain materials. Most of the code, textures, and models for decorating have already been removed anyway. Sorry. I hated to remove it too, but I believe this was the best result.
