### ISSUE TITLE
{Question}: Why is the Enchantment glint removed?

### ISSUE THREAD

**Issue by Akitori** [SilentChaos512/SilentGems#275]
Why in the newest versions of Silent's Gems are enchantment glints missing from all tools/weapons/armor?

Could we have a config option to enable that?

**Comment by SilentChaos512** [comment]
Because Minecraft adds the effect to every layer of the model, so you get the effect stacked 4-6 times. It's not pretty. This has been the case since Minecraft 1.8 or 1.9, I forget which. I have never been able to find a fix for this.

It's something like this:
![2018-01-13_15 43 41](https://user-images.githubusercontent.com/5721949/34910358-b70d8560-f878-11e7-9aa6-f6c3b19e2aa9.png)

**Comment by Akitori** [comment]
Ah i see. I would like that feature if possible, but i understand it'll be difficult. (That and the whole overlaying enchantments might hurt people's eyes.)

I am curious as to how that looks myself.

**Comment by Akitori** [comment]
Is it bad i actually like that look myself? It looks pretty awesome! And with quark i can change the color of the glints to whatever i want. 

Though i wouldn't enjoy it for my pickaxes...I kinda want something the invert of the old flint upgrade. A shiny case that shows enchantment glints on items when applied.

Just my feedback at least.

**Comment by SilentChaos512** [comment]
Well, if nothing else I could add a config to re-enable glints. I'll look into it when I have some time.

**Comment by Akitori** [comment]
Thanks!
