### ISSUE TITLE
[Suggestion] Compatibility with other mods repair options

### ISSUE THREAD

**Issue by GamertechAU** [SilentChaos512/SilentGems#331]
Currently making a 1.12.2 modpack including Silent's Gems and Evilcraft, and was planning on using EC's Blood Chest to repair SG tools, but apparently they aren't compatible.

Any chance of expanding SG's tool repair system to be compatible with other repair options such as this?

**Comment by SilentChaos512** [comment]
Looks like this will be easy enough to fix, EvilCraft provides an API for me to work with. This doesn't work already because Gems' tools have to marked as "not repairable", otherwise players could destroy their tools with the vanilla repair recipe (craft 2 damaged tools together, get 1 with all the essential data missing).

**Comment by GamertechAU** [comment]
Ah yea, I can see how crafting two tools together would be an issue. Thanks for looking into this mate.

**Comment by GamertechAU** [comment]
Blood chest is working perfectly for both tools and armour. Cheers Silent
