### ISSUE TITLE
Crash when generating world / entering world.

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/SilentGems#361]
### Versions

- **Silent's Gems**: 3.0.9+24 
- **Silent Lib**:  4.0.6+19 
- **Forge**: 25.0.99 
- **Modpack** (if applicable): Custom

### Expected behavior
loading up as normal

### Actual behaviour

game crashes when joining world / generating a new world.

### Links/Images
- [hastebin](https://hastebin.com/mocadetala
)
### Steps to reproduce the problem

1. create a world
2. join it
3. crash

**Comment by SilentChaos512** [comment]
Does this happen every time, or just occasionally? I believe this is a Forge bug. It happens to maybe 5~10% of launches for me.

**Comment by Gbergz** [comment]
It didn’t happen first, but then the next 4-5 launcher it happens.

sun 31 mars 2019 kl. 03:51 SilentChaos512 <notifications@github.com>:

**Comment by SilentChaos512** [comment]
Looks like the fault of another mod. I found Forge issue 5645, which points to an issue you created for the level-up-hp mod. Basically identical crash report, and I know my capabilities are not returning null.

For now, it looks like disabling mods to find the culprit is the only solution. One thing you might try is using NBT Explorer to look at what capabilities are attached to your player. That might narrow it down. That, or just wait for sargunv's patch to be merged into Forge, which will point to the mod at fault.

(edit) I suggest leaving this issue open until we get that patch.
