### ISSUE TITLE
[1.14.3] Unable to connect to a dedicated server with only silent gems installed. Internal Exception:

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/SilentGems#378]
Five hours of troubleshooting later...I have it!

Forge gives absolutely no info in the client or the server, only this one message on the client screen-

Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

![ba353ea24d161619afc3a830d389488c](https://user-images.githubusercontent.com/4427684/60538137-31d55400-9cc7-11e9-8d36-dad05b418c3e.png)

I tested with only Silent Gear and you can connect without problems.

## Versions

- **Silent's Gems**: SilentGems-1.14.3-3.2.0+44
- **Silent Gear**: SilentGear-1.14.3-1.2.0+40
- **Silent Lib**: SilentLib-1.14.3-4.2.0+31
- **Forge**: forge-1.14.3-27.0.16
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/ocean-islands-adventure

**Comment by SilentChaos512** [comment]
Seems to be caused by token enchanter recipes, although I'm not sure why exactly. As you said, there is no information logged on either side, aside from the type of the exception. I'll probably have to make a custom Forge build to debug this...

If you want a temporary "fix", deleting all token enchanter recipes from the JAR should work. They're all found in `data/silentgems/recipes/token_enchanting`.

**Comment by SilentChaos512** [comment]
Found the problem, expect an update later today. I'm going to spend a little time testing on a server, see if I can spot any other obvious issues.
