### ISSUE TITLE
[1.9] Flower Pots causing horrendous FPS loss

### ISSUE THREAD

**Issue by b0bst3r** [SilentChaos512/SilentGems#40]
Forge 1907
SilentLib-1.9-1.0.7-13
SilentsGems-1.9-2.0.11-29

I placed 8-10 chaos flower pots in a 3x5 chunk area at various spots.  After placing them, my FPS started to take a hit and after the phantom lights started spreading, my fps nosedived.  I went around and broke all the pots, the phantom lights seemed to disappear but my FPS is still suffering days and couple of reboots later, as if there is something invisible causing issues in the world.  All of this ofc done in SMP.

Reported by another player not me, but I went to his base and the FPS is terrible, having 120 at one point then 1-3 at another.  Nothing recorded in console/log just bad FPS hits.

**Comment by SilentChaos512** [comment]
I'm not sure what could cause such a big FPS drop here, especially on a server. All phantom lights should disappear within a minute of the pot that spawned them being removed. Particles from the lights should be the only thing affecting FPS in this case.
I've made a build that logs all pot and light tile entities every minute ([Dropbox link](http://bit.ly/1suWr7b)). Try running the server a few minutes (offended area loaded, of course) and send me the log, please.

**Comment by DoomSquirter** [comment]
I'm the affected person on the server.

The phantom lights did disappear within a minute of the pots being broke, but the FPS hit started before I broke any pots which led to me breaking them.  

Sever has been rebooted multiple times and the issue persists.  

No lights are seen per se.  The most tell tale sign that there is an issue is when you place/break blocks in the area.  your fps will go down to 2 and everything starts to stutter.

Furthermore, every so often, turning or viewing certain areas of the building will cause the same 2 fps issue.  

All of the above were not happening prior to placing those pots down.  We'll test the server build and see if they show up in the log, otherwise I guess I will have to move lol.  

Thanks alot for a fantastic mod btw.  Everyone loves it.

**Comment by DoomSquirter** [comment]
So, I'm fairly certain the issue was cooincidental but unrelated to your mod.  I think you can close the issue.

I had prior to putting down the pots, redid my floor in chisel blocks and have now confirmed that it's chisel causing the fps drop, not the pots.  

The log file showed no hits for the duration while I was on the server using the dropbox'd version.

I apologize for the mixup.  It's quite difficult to pinpoint issues in 1.9 with so many red herrings.

**Comment by SilentChaos512** [comment]
No problem, I'm glad the issue was resolved. I know all too well how difficult it can be to pin down an issue in modded.
