### ISSUE TITLE
"Fluffy Puff" Flower doesn't have a unique hitbox, and doesn't show in HWYLA like the other SG flowers

### ISSUE THREAD

**Issue by fzzyhmstrs** [SilentChaos512/SilentGems#505]
SilentGems-1.16.3-3.7.1+104
SilentGear-1.16.3-2.3.0+165
SilentLib-1.16.3-4.8.1+61
Forge: 34.1.0
Modpack: No, but there are other mods installed like JEI, HWYLA, etc
No Optifine

Expected the flower that gives "fluffy puff" seeds to have a custom hitbox, adn to show up in HWYLA like the glowroses do.

the "fluffy puff" flower has a 1 block hitbox (entire block), and doesn't show up on HWYLA, even though the green sapphire glowrose right next to it does.

Images of the two flowers with hitboxes showing and HWYLA behavior
![2020-10-18_09 54 24](https://user-images.githubusercontent.com/72876796/96369536-a33d4e00-1128-11eb-9188-66784bdd30e2.png)
![2020-10-18_09 54 26](https://user-images.githubusercontent.com/72876796/96369555-b9e3a500-1128-11eb-8a75-f61a07a76e41.png)

Very simple to reproduce. Look at the flower, and the behavior doesn't seem right compared to the others.

**Comment by SilentChaos512** [comment]
Info HUD mods like HWYLA do tend to struggle with blocks that have no item, like crops. I'll see if I can at least make it show the seeds. Probably just need to override `getPickBlock`.

The reasoning behind the hitbox is that it's the default for all crops, so I never changed it. Guess I could at least make the wild version smaller, since it is technically not a crop.
