### ISSUE TITLE
Reduce number of gems available in 1.17

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/SilentGems#513]
## Versions

- Minecraft 1.17.x

## What Should Be Added or Changed?

The overall number of gems should be reduced significantly. Possibly to just 16. The single set could be divided up between dimensions. One suggestion I had on Discord was to 4 per vanilla dimension, with 2 being rare in the overworld and common in the Nether, and another two like that for the End dimension. Something like that sounds like a good choice. It would lead to six types per dimension with the overlap.

### What Gems Should Stay?

Probably a mix of gems common to other mods and some unique ones. **Suggestions welcome.**

Amethyst should be removed because vanilla is adding it. Silent Gear will handle the material for it.

#### Possible list

Trying to stick with the typical spectrum of colors that the current version uses, just so there is a good palette for building blocks.

- Ruby (red)
- Carnelian (red-orange)
- Topaz (orange)
- Citrine (orange-yellow)
- Heliodor (yellow)
- Moldavite (yellow-green)
- Peridot (green)
- Turquoise (mint green)
- Kyanite (cyan)
- Sapphire (blue)
- Iolite (indigo)
- Alexandrite (violet)
- Ammolite (magenta)
- Rose Quartz (pink)
- Black Diamond (Nether)
- White Diamond (replacing yellow diamond in the End)

#### Possible sets

- Overworld
    - Ruby
    - Topaz
    - Peridot
    - Sapphire
    - Heliodor (rare, shared)
    - Turquoise (rare, shared)
    - Iolite (rare, shared)
    - Alexandrite (rare, shared)
- Nether
    - Carnelian
    - Citrine
    - Moldavite
    - Iolite (shared)
    - Alexandrite (shared)
    - Black Diamond (somewhat rare)
- End
    - Heliodor (shared)
    - Turquoise (shared)
    - Kyanite
    - Ammolite
    - Rose Quartz
    - White Diamond (somewhat rare)

## Why Should This Be Done?

While the variety of the current 48 gemstones is nice, it is a bit overwhelming. Many of the gems are not particular useful and just end up being used as "trash" gems for repairs and random crafting ingredients. Working on the gear materials (setting stats and traits, adding part type support) is painful due to how many there are. Having fewer will allow more work to be done on that, making each gem more unique.

The removal would also cut hundreds of blocks and items from JEI and from the registries, as well as many textures, reducing the memory footprint of the mod. This would also remove many more hundreds of JSON files. The JSON files alone will reduce the JAR file size quite a bit.

**Comment by unmoving-javi** [comment]
In all honesty I think having one gem just for repairs would also be fine, though I suppose that's down to personal opinion, and obsidian kinda fills that role decently well.
Any gem without any sort of special ability should probably be cut though, having gems with JUST Brittle V is kinda questionable.
In any case, that's just my two cents on the idea. Feel free to do whatever you want with the feedback.

**Comment by spiritofodysseus** [comment]
I personally like the amount of gems currently, although I will admit I have spent too much time figuring out great combinations for all the different gears, weapons, and tools (literally a whole day per set, it's pretty crazy actually).

If possible, perhaps KEEP all of the gems but only make a few (16?) rare which have a qualified role with attributes whilst the other gems being much more common but which are useless(as decoration), tiered 1-3 for repairs, and/or on the same basic level as +/- iron is now. I honestly dislike the idea of taking away what makes "Silent's Gems" what it is, but I do understand the need to make your life as the owner easier. I hope you take my idea into consideration.

**Comment by yggdrasil75** [comment]
naj77 requested I post this here instead. I would like to keep the existing gems available and just change up how they work. if you disagree with this idea, perhaps just split the removed gems into a "extra gems" mod that you only update once per mc version (since if they are just items that is how often they would need updates - dont need to implement chaos versions of them or anything)


the differences for dark set stats could be more extreme than overworld (ie: overworld durability range have at ~300-1000, nether set have at 50-3000 and to balance, harvest speed also be similar and all other stats - 4 armor min for dark set, 30 armor max, while overworld is 8-18 and so on), while light set should be moved to t4 with stats to match. crimson iron and azure silver should as well, and tyrian steel, crimson steel, azure electrum, and a few other t4 should be raised to t5. t3 would lose a few if you are using gear without gems (still have some, just not as many), but if you have gems, or any number of other mods (ie: thermal series, wyrmroost, just gems, netherrocks, iafgear, etc.) then you still have t3. and even if you dont have those, you still have diamond, emerald, obsidian at the very least.

for reference about t3 losing: I have 151 t3 main parts according to the materials dump. subtract 16 due to light set shift, and I still have well over 100. a midsize modpack will not lose anything with the tier shift of gear materials.


maybe for the nether set, "associated traits" should be opposites, high armor means low armor durability, and vice-versa?

as for the traits, I dont know what is possible for that and have no real new ideas. beyond maybe having green gems (green sapphire) add looting, while purple add luck (sapphire) my only though is look at the enchants apotheosis adds and maybe rip some of those off?

**Comment by yggdrasil75** [comment]
got an idea for a gem trait: when used for arrows or slingshot ammo it teleports user to where it lands.

**Comment by najlitarvan** [comment]
> naj77 requested I post this here instead. I would like to keep the existing gems available and just change up how they work. if you disagree with this idea, perhaps just split the removed gems into a "extra gems" mod that you only update once per mc version (since if they are just items that is how often they would need updates - dont need to implement chaos versions of them or anything)
> 
> the differences for dark set stats could be more extreme than overworld (ie: overworld durability range have at ~300-1000, nether set have at 50-3000 and to balance, harvest speed also be similar and all other stats - 4 armor min for dark set, 30 armor max, while overworld is 8-18 and so on), while light set should be moved to t4 with stats to match. crimson iron and azure silver should as well, and tyrian steel, crimson steel, azure electrum, and a few other t4 should be raised to t5. t3 would lose a few if you are using gear without gems (still have some, just not as many), but if you have gems, or any number of other mods (ie: thermal series, wyrmroost, just gems, netherrocks, iafgear, etc.) then you still have t3. and even if you dont have those, you still have diamond, emerald, obsidian at the very least.
> 
> for reference about t3 losing: I have 151 t3 main parts according to the materials dump. subtract 16 due to light set shift, and I still have well over 100. a midsize modpack will not lose anything with the tier shift of gear materials.
> 
> maybe for the nether set, "associated traits" should be opposites, high armor means low armor durability, and vice-versa?
> 
> as for the traits, I dont know what is possible for that and have no real new ideas. beyond maybe having green gems (green sapphire) add looting, while purple add luck (sapphire) my only though is look at the enchants apotheosis adds and maybe rip some of those off?

or maybe the gems could only have tooltip slots and the textures with worldgen config or datapacks for it, then make a datapack with the stadart values and let people modify that datapack for their own usage

**Comment by sophienix** [comment]
why did you guys removed apatite it was realy good with fortune adding up to 8x daimonds
