### ISSUE TITLE
Gravity enchant over 3 makes mining time infinite

### ISSUE THREAD

**Issue by abint** [SilentChaos512/SilentGems#540]
## Versions

- **Silent's Gems**: 1.16.3-3.7.14
- **Silent Gear**: 1.16.3-2.6.19
- **Silent Lib**: 1.16.3-4.9.6
- **Forge**: 36.1.9
- **Modpack**: FOG of magic
- **Optifine Installed**: No

## Expected Behavior
When the gravity enchant is above 3, it would be expected that either the mining speed while off the ground gets increased even further beyond grounded speeds, or it gets capped at grounded speeds

## Actual Behavior
Mining time gets so low that mining time becomes infinite

## Steps to Reproduce the Problem

1. Grant an item gravity 4 or above via commands, apotheosis enchanting module, resplendent prism, quark ancient tome, etc
2. Float off the ground
3. Mine using said item

**Comment by SilentChaos512** [comment]
Okay, so the speed multiplier is calculated as `5 / (maxLevel - level + 1)`. So the divisor does become zero or negative if level is greater than the max enchantment level. I already knew from a Token Enchanter issue that Apotheosis doesn't change the actual max level that enchantments claim they have, so that's the issue.

I guess the most logical solution is to just clamp the level between 1 and 3, since the enchantment is only meant to negate the speed penalties. Then maybe I could add a small bonus for levels that fall outside the normal logic.
