### ISSUE TITLE
Add gems from 1.12.2 versions

### ISSUE THREAD

**Issue by Kasia1403** [SilentChaos512/SilentGems#550]
## Versions

- Minecraft 1.18 and newer ( when they come out ) and I would like it to be for Forge more than Fabric

## What Should Be Added or Changed?
 
(Description here) All gems from 1.12.2 versions 

## Why Should This Be Done?

(Description here) It will be more coloured gems to find and collect and these gems will be to craft swords and armor like it was in MC 1.12.2

**Comment by SilentChaos512** [comment]
No, I'm not undoing the change. Fewer gems makes maintaining the mod so much more manageable.

Read this issue: https://github.com/SilentChaos512/SilentGems/issues/513

**Comment by Kasia1403** [comment]
Hm... Looks like You maybe are after COVID-19 and You are very tired because of this. ( ? )

**Comment by Kasia1403** [comment]
Could You answer, please ?

**Comment by Kasia1403** [comment]
> This has been closed. please just let it go and stop bothering silent,

Is SilentChaos512 tired because of COVID-19 or why he doesn't want to add more gems ? I don't understand him.

**Comment by Kasia1403** [comment]
Could someone explain me how to create similar mod ?

**Comment by SilentChaos512** [comment]
For one thing, having to make 48+ textures every time I wanted to add something to the mod was tedious. I also have much less free time, since I have a full time job and other things going on in my life now.

Fewer gems also means that assigning traits is easier. Making the materials unique is possible now. I could never come up with unique traits for all 48 gems.

If you want to make a mod that adds the removed gems back, you're welcome to do so. There are modding tutorials on the Internet. But you will need to learn Java. All the code for Silent's Gems is right here on GitHub, if that helps you. You're welcome to reference it for your own code.

I didn't even want to grace you with a response on the COVID bit, but... I don't know what things are like where you live, but people didn't fall for the propaganda as much where I live. So the virus has had very little impact on my life. There are some crazy people out there still, but most people stopped even wearing masks almost a year ago.

**Comment by Kasia1403** [comment]
Hello SilentChaos512, hve You heard about new omicron variant of coronavirus and also that COVID-19 may not give You any syptoms ? And what if You have COVID-19 but You don't know about it ? You should better go for test and if the test will be negative then You should go vaccinate Yourself and also Your family.

**Comment by SilentChaos512** [comment]
Now I regret responding at all. Thanks, and go fuck yourself. I won't tolerate your nonsense.
