### ISSUE TITLE
Support for Lumberjack Mod?

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/SilentGems#62]
This is a mod that adds lumberjack axes to the game based from mods that already adds axes, but it doesn't work with this mod. 
Reported at DoubleDoorDevelopment/Lumberjack#12

**Comment by SilentChaos512** [comment]
Not fixable, unfortunately. The Lumberjack mod wants unique axe items with unique tool materials assigned to them. Gems 2 uses a single item for all axes (because they are modular), and the diamond material (because I needed to select something).

However, all super-tier axes in Gems have a lumberjack skill that can be toggled on/off at will. So, that's an option at least. Sorry I can't do anything else.

**Comment by WenXin20** [comment]
Thats Ok, thanks anyway
