### ISSUE TITLE
[Bug] Silent's refusing to play nice with JEI and CraftTweaker

### ISSUE THREAD

**Issue by MysticAura** [SilentChaos512/SilentGems#80]
MC: 1.10.2
Forge: 2121
Mod Version: SilentsGems-1.10.2-2.1.4-83
Related mods: CraftTweaker-1.10.2-3.0.15, jei_1.10.2-3.13.3.376

Issues: 

- JEI click to delete functionality refuses to delete Silent's tools, they just drop to the ground when it's attempted ([related bug report](https://github.com/mezz/JustEnoughItems/issues/624))
- Removed tool recipes are still craftable even though JEI and CraftTweaker have definitely removed the recipes ([related bug report](https://github.com/jaredlll08/CraftTweaker/issues/90))

The common thread between these is Silent's so I felt you should take a look as well to see what's going on with the failed interactions. Thank-you for your time

**Comment by SilentChaos512** [comment]
- I'm aware of the JEI issue. It's been a problem ever since I started the rewrite (Silent's Gems 2). Something to do with NBT, if I had to guess.
- The recipes you see in JEI are _not_ what gets used in crafting. There's a hidden recipe handler that allows the creation of multi-gem tools. That recipe handler overrides anything you see in JEI. So removing the "example recipes" has no effect.

I'm curious what tools you are trying to disable. I might be able to do something about that.

**Comment by MysticAura** [comment]
Did you add/alter the hidden handler recently? Because this method in crafttweaker used to fully work. Whereas now it only 'hides' the recipe instead of fully removing it. If I list the recipes on a tool with mt recipes hand, it shows only the recipes I've left intact. So I'm guessing crafttweaker can't see the hidden handler recipes either.

The items I'm removing are pretty much everything not requiring a supercharged gem... axe, pickaxe, shovel, hoe, sickle, weapons, armor, shields.. I'd only like the supercharged versions available in the pack.

Even if each had a normal item and a supercharged item, it would make for disabling and hiding a certain tier much easier for pack devs. For the record though, I find how you merged each into 1 impressive and genius to be honest, however the extremity of it has lead to complication when it comes to unraveling them from each-other.

**Comment by SilentChaos512** [comment]
Multi-gem tools (and therefore the custom recipe handler) were added in 2.0.0 (or Minecraft 1.9). So not exactly a recent addition, but at the start of the rewrite. Incidentally, that was the primary reason the mod was rewritten in the first place.

I can add some configs to allow tool parts to be disabled though. I'll add configs for each tier and tool type, so you will just need to disable mundane and regular tiers. I'll also throw in a general-purpose blacklist, just in case anyone needs it.

Just for reference, the reason each tool type is one ID is because of the modular (multi-gem) recipes. Registering the 65,536+ variants of pickaxes alone as separate items would have impossible (I think that's the cap on items ID's), or at least a very bad idea. And that number doesn't account for parts registered by add-ons, which can be mixed with gems. So most data on the tool's construction needs to be in NBT.
