### ISSUE TITLE
[Bug] Server crash - ticking block entity

### ISSUE THREAD

**Issue by MysticAura** [SilentChaos512/SilentGems#84]
MC: 1.10.2
Forge: 2151
Mod Version: SilentsGems-1.10.2-2.1.5-84

Not sure what triggered it. All players were kinda baffled and thought I'd restarted without announcing. It was fine after restart (luckily) CME's really do seem random when they happen though. It seems at some point every mod triggers at least one.

[Crash Log](http://pastebin.com/ptJ15886)
Update:
[Crash Log 2](http://pastebin.com/1SJzi8hY)

**Comment by MysticAura** [comment]
Forge: 2166
Mod Version: SilentsGems-1.10.2-2.1.6b-87

Unfortunately I just had this happen again while testing my next pack update. Could be coincidence but it seems to happen most often when having just teleported.

[Crash Log](http://pastebin.com/VzqepxvS)

**Comment by SilentChaos512** [comment]
Teleporting can cause multiple hostile mobs to despawn suddenly, so I can see how that would cause the crash. I've never fixed this kind of issue before, but I think I've got it this time. Look for version 2.1.6c to show up in a few minutes.

**Comment by BluSunrize** [comment]
Sorry for butting in here, but looked over that commit and wanted to voice an idea if that's okay?
I don't know how many iterations this issue and its fixes have gone through, so I don't know if this was suggested or tried before.
In order to avoid the use of the loadedEntityList, have you considered using `getEntitiesWithinAABB(Class <? extends T > classEntity, AxisAlignedBB bb)`?
Would still allow for checking for EntityMob and instead of a predicate to check distance, you'd parse an AABB based on position and distance? I've yet to encounter CMEs in using those myself, so I assume they are thread safe?

**Comment by MysticAura** [comment]
So far so good. I haven't been able to trigger it in your updated version. I'll let you know if it happens again.

**Comment by SilentChaos512** [comment]
@BluSunrize Thanks for the suggestion, I'll try that if the problem persists.
