### ISSUE TITLE
Request - Add direct support of Tconstruct

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SilentChaos512/SilentGems#89]
I love your mod but despite that it has no support for a mod 90% of my players won't play without and that is Tconstruct. Can you please add direct Tconsupport?

**Comment by SilentChaos512** [comment]
Why? It would make most of my mod pointless.

**Comment by SilentChaos512** [comment]
I'm not mad, I'm just curious if there is a valid reason to do this. I've shot down this idea in the past because I can't think of any reason to go through with it.

**Comment by P3rf3ctXZer0** [comment]
Okay so essentially if you added support for your ores or a way to break your axes and stuff into pieces people could mix and match for different effects. I think passed on your enchantment coins etc it would be great to be able to use them to prevent a pick axe or tool from breaking and the fact that you have unique enchantments etc would be awesome to apply to a tcon tool. Overall it just adds a layer of balance between your mod and other mods. It will also increase your user base for sure.

**Comment by M4thG33k** [comment]
I'm going to preface this with the following: although TCon and Gems are different mods with a similar tool mechanic, they both have a different "feel" to them. IMO, TCon is basically meant as a tool-building mod while Gems has more non-tool content that you will miss out on if you don't pay attention. The Chaos mechanic, teleporters, return home charm, and armor of Gems really sets it apart from TCon. If someone doesn't want to use these extra features, they're missing out and I pity them.

That being said, I too would also be interested in TCon support for one particular reason: options.

You prefer having as many options to choose from when creating tools (or basically anything) while playing Minecraft. The more options one has for Tinker's tools, the harder it is to find a "perfect" combination of materials to make the tool. 

It would be interesting to see different Gems having different properties when used as TCon parts, and you could keep your mixed-gem properties by allowing "alloys" to be formed from the gems in a smeltery. 

Granted, I understand all of this is probably not an easy task and therefore do not expect any/all of it to happen, but it would be nice to see. Thanks for the great mod, Silent and I'll respect whichever direction you plan to take with it.

**Comment by P3rf3ctXZer0** [comment]
@M4thG33k I have to say your answer is by far thought out more clearly than mine.

**Comment by SilentChaos512** [comment]
I meant to respond to this a bit sooner than I did... But M4th's reasoning makes perfect sense to me. Both mods have their strengths and weaknesses. For example, TCon tools have greater diversity and a large existing user base, while Gems' tools have better cross-mod compatibility (since they extend vanilla tool classes).

I'll start working on TCon support sometime soon, probably for 2-3 updates from now. I've been discovering a lot of server-specific bugs lately, so I'm working on those at the moment. Note that I've never worked with TCon before, so this might take some time.

Two things I'd like to mention though: Gems' tools do not break, same as TCon tools. Also, TCon tools don't allow enchantments because their upgrade system fills the same role, and I intend to respect that. So no tokens on TCon tools.

**Comment by P3rf3ctXZer0** [comment]
Any specifics I can crush for you?

**Comment by M4thG33k** [comment]
Yeah, if you want any help with ideas for material traits, let me know and I can try to come up with something...

**Comment by SilentChaos512** [comment]
Help selecting traits would be nice, thanks. Also if someone could point me in the direction of an open source mod that add tool materials, that would be helpful. My early attempts have not been working out.

**Comment by M4thG33k** [comment]
I think this is what you're looking for (although it might be slightly outdated since I don't see how to create your own traits listed): https://gist.github.com/bonii-xx/e46f9d9e81e29d796b1b

If you don't want to have dozens of different material traits (which would arguably be pretty cool), you could have all the Gem tools have something like a "Bejeweled" trait which causes the tool to not take damage and/or have a mining boost when mining any Gems ore. I'll keep thinking of unique traits though.

**Comment by P3rf3ctXZer0** [comment]
Thank you will start testing it a bunch.
